version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-flutter
    restart: unless-stopped
    ports:
      - "8080:8080"   # Jenkins
      - "5000:5000"   # Flutter Web
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
